emily_home:
    pattern: /
    defaults: { _controller: emilyBoutikBundle:Home:show }
    requirements:
        _method: GET

emily_contact:
    pattern: /contact
    defaults: { _controller: emilyBoutikBundle:Contact:show }
    requirements:
        _method: GET|POST

emily_products:
    pattern: /products
    defaults: { _controller: emilyBoutikBundle:Products:all }
    requirements:
        _method: GET

emily_category:
    pattern:  /{id}
    defaults: { _controller: emilyBoutikBundle:Categories:show }
    requirements:
        _method: GET
        id: \d+