parameters:
#    emily_entities_product.example.class: emily\entities\ProductBundle\Example

services:
#    emily_entities_product.example:
#        class: %emily_entities_product.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
